security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        in_memory:
            memory:
                users:
                    admin_api:
                        {
                            password: "$2y$13$FyFru.g9yWtBZYKHOBKVuur0r9JeKQHTnXe1eFLNJgOwiaGN5adsO",
                            roles: ROLE_SUPER_ADMINISTRATOR,
                        }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_public:
            pattern: ^/api
            security: false
        # api_login:
        #     pattern: ^/api
        #     user_checker: App\Security\UserChecker
        #     anonymous: lazy
        #     provider: all_app_users
        #     json_login:
        #         check_path: app_api_security_login
        main:
            anonymous: false
            lazy: true
            provider: app_user_provider
            guard:
                authenticators: [App\Security\LoginAuthenticator]
            logout:
                path: app_logout
    access_control:
        - { path: /.$, roles: IS_AUTHENTICATED_ANONYMOUSLY } # para la `/` solamente !
        # - { path: ^/home, roles: [IS_AUTHENTICATED_FULLY, ROLE_ADMIN] }
        - { path: ^/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - {
              path: ^/telecomunicaciones/factura/print-facturas-pospago,
              roles: IS_AUTHENTICATED_ANONYMOUSLY,
          }
        - {
              path: ^/dtone,
              roles: IS_AUTHENTICATED_ANONYMOUSLY,
          }
        - { path: ^/.+, roles: [IS_AUTHENTICATED_FULLY] } # todos loq ue tengan datos despeus de /
